# <font color="blue">Data Preprocessing : Encoding and Feature Scaling avec Python
La qualité des données est un élément clé dans toute démarche de machine Learning. Toutefois, Le plus souvent, en machine Learning, les jeux de données (Data Set) proviennent avec des ordres de grandeurs différents ce qui peut affaiblir les performances de modélisation (en particulier la lenteur de la convergence d'un algorithme).  

Le Feature Scaling qui comprend la Standardisation et la Normalisation permet de pallier à ce genre de problème (différence d'echelle des grandeurs).

Les jeux des données peuvent nécessiter dans pas mal de situations la transformation (encodage) des caractéristiques catéorielles (qualitatives) en valeurs numériques(quantitatives)pour que l'on passer passer à un estimateur.

Dans ce Colab, je  présente comment faire Encoding and Feature Scaling des données en utilisatnt le module [sklearn.preprocessing de python](https://scikit-learn.org/stable/modules/classes.html highlight=preprocessing#module-sklearn.preprocessing).</p>

 # <font color="blue"> 1. Encodage des données</font>

Le module preprocession du package Sklearn du Python dispose de plusieurs *Transformer Classes* qui permettent l'encodage (ou transformation) des données dont je présente les suivants:

* **Encodage Ordinal:** Permet d'associer chaque valeur catégorielle (ou classe) à une <font color="orange">valeur décimale</font>. Je me limite aux deux classes suivantes:
* **Encodage One-Hot:**  ermet d'associer chaque valeur catégorielle (ou classe) à une <font color="orange">valeur binaire (suite de bits)</font>.



<font color="blue">1.1. Encodage ordinal</font>
+ ***LaberEncoder():*** encode chaque valeur catégorielle de Y en valeur décimale (0, 1, 2, ..)

In [ ]:
#Exemple 1
import numpy as np
from sklearn.preprocessing import LabelEncoder
"""
Encodage des données avec LaberEncoder()
"""

Y=np.array(["Homme",
            "Homme",
            "Femme",
            "Homme"])
#utilisation d'un transformateur Ordinal LaberEncoder()
encoder=LabelEncoder().fit_transform(Y)
print("Les valeur catégorielles de Y sont: \n",Y)
print("Les valeur décimales associées aux valeurs\
catégorielles de Y sont: \n",encoder)

Les valeur catégorielles de Y sont: 
 ['Homme' 'Homme' 'Femme' 'Homme']
Les valeur décimales associées aux valeurscatégorielles de Y sont: 
 [1 1 0 1]


In [ ]:
#Exemple 2
import numpy as np
from sklearn.preprocessing import LabelEncoder
"""
Encodage des données avec LaberEncoder()
"""

Y=np.array(["chat",
            "chat",
            "souris",
            "chien",
            "souris"])
#utilisation d'un transformateur Ordinal LaberEncoder()
encoder=LabelEncoder().fit_transform(Y)
print("Les valeur catégorielles de Y sont: \n",Y)
print("Les valeur décimales associées aux valeurs\
catégorielles de Y sont: \n",encoder)

Les valeur catégorielles de Y sont: 
 ['chat' 'chat' 'souris' 'chien' 'souris']
Les valeur décimales associées aux valeurscatégorielles de Y sont: 
 [0 0 2 1 2]


<font color="red">**Attention:**</font> LabelEncoder() prend en paramètre un vecteur, sinon on aura une erreur d'exécution.

+ ***OrdinalEncoder():*** encode les valeur catégorielles de la variable X en valeurs décimales (0, 1, 2, ..)

In [ ]:
#Exemple 3
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
"""
Encodage des données avec OrdinalEncoder()
"""

X=np.array([
            ["chat", "Poile"],
            ["chat", "Poile"],
            ["oiseaux","plume"],
            ["chien", "poile"]])
#utilisation d'un transformateur Ordinal LaberEncoder()
encoder=OrdinalEncoder().fit_transform(X)
print("Les valeur catégorielles de X sont: \n",X)
print("Les valeur décimales associées aux valeurs \
catégorielles de X sont: \n",encoder)

Les valeur catégorielles de X sont: 
 [['chat' 'Poile']
 ['chat' 'Poile']
 ['oiseau' 'plume']
 ['chien' 'poile']]
Les valeur décimales associées aux valeurs catégorielles de X sont: 
 [[0. 0.]
 [0. 0.]
 [2. 1.]
 [1. 2.]]


<font color="blue">1.2. Encodage One-Hot</font>



+ **LabelBinerizer :**


In [ ]:
#Exemple 4
import numpy as np
from sklearn.preprocessing import LabelBinarizer
"""
Encodage des données avec LabelBinarizer()
"""
Y=np.array(["chat",
            "chat",
            "souris",
            "chien",
            "souris"])
#utilisation d'un transformateur One-Hot: LabelBinerizer()
encoder=LabelBinarizer().fit_transform(Y)
print("Les valeur catégorielles de Y sont: \n",Y)
print("Les valeur binaires associées aux valeurs\
 catégorielles de Y sont: \n",encoder)

Les valeur catégorielles de Y sont: 
 ['chat' 'chat' 'souris' 'chien' 'souris']
Les valeur binaires associées aux valeurs catégorielles de Y sont: 
 [[1 0 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]]


+ **OneHotEncoder :**

In [ ]:
#Exemple 5
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer
"""
Encodage des données avec OneHotEncoder()
"""
X=np.array([
            ["chat", "Poile"],
            ["chat", "Poile"],
            ["oiseaux","plume"],
            ["chien", "poile"]])
#utilisation d'un transformateur MultiLabelBinarizer()
encoder=OneHotEncoder().fit_transform(X)
print("Les valeur catégorielles de X sont: \n",X)
print("Les valeur Binaires associées aux valeurs \
catégorielles de X sont: \n",encoder)

Les valeur catégorielles de X sont: 
 [['chat' 'Poile']
 ['chat' 'Poile']
 ['oiseaux' 'plume']
 ['chien' 'poile']]
Les valeur Binaires associées aux valeurs catégorielles de X sont: 
   (0, 0)	1.0
  (0, 3)	1.0
  (1, 0)	1.0
  (1, 3)	1.0
  (2, 2)	1.0
  (2, 4)	1.0
  (3, 1)	1.0
  (3, 5)	1.0
