<a href="https://colab.research.google.com/github/elhaji1/machine-learning/blob/main/Perceptron_simple_1_ET_Logique.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Perceptron Simple pour le problème de "ET Logique"




##Importer les fonctions nécessaires

In [20]:
from random import choice
from numpy import array, dot, random


*   random.[choice(list)](https://https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html) : Return a random element from a list <br>
Look at the following example:



In [21]:
cours = ["Réseaux de neurones", "Machine Learning", "Python", "Data mining"]
choice(cours)

'Machine Learning'

##La fonction heaviside

In [22]:
def heaviside(x):
  if x<0:
    return 0
  else:
    return 1

##Données:
$([x1, x2, x0], y)$: $x0$ représente le bias

In [23]:
training_data = [
    (array([0,0,1]), 0),
    (array([0,1,1]), 0),
    (array([1,0,1]), 0),
    (array([1,1,1]), 1),]

## Génération des poids synaptiques $Wi$

In [24]:
w = random.randn(3)

## Training (Mise à jour des $Wi$ )


In [25]:
errors = []
eta = 0.2 #learning_rate
n_iteration = 100 
for i in range(n_iteration):
    x, y = choice(training_data) #Tirer aléatoirement un élément du dataset
    z = dot(x, w)
    error = y - heaviside(z)
    errors.append(error)
    w += eta * error * x

##Utilisation du modèle ainsi entrainé pour la prédiction:
Maintenant les $Wi$ sont bien appris, c'est le temps de l'utiliser!!

In [34]:
test_data = [
             array([1,0,1]),
             array([0,1,1]),
             array([1,1,1]),]

In [35]:
for x in test_data:
    z = dot(x, w)
    print("{}: {} -> {}".format(x[:2], z, heaviside(z)))

[1 0]: -0.5619818587005467 -> 0
[0 1]: -0.36263514086725146 -> 0
[1 1]: 0.07183175738139203 -> 1
